name: update-matches

on:
  schedule:
    - cron: '00 23 * * SUN,MON,THU'
  workflow_dispatch:

jobs:
  run-sims-script:
    name: Run R script and output matches csv
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ~/.R/library

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Set R library path
        run: echo "R_LIBS_USER=${HOME}/R/library" >> $GITHUB_ENV

      - name: Install R packages
        run: |
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE, showWarnings = FALSE)
          install.packages(c("tidyverse", "remotes"), lib=Sys.getenv("R_LIBS_USER"), repos="https://cran.rstudio.com/")
          remotes::install_github("JaseZiv/worldfootballR", lib=Sys.getenv("R_LIBS_USER"))
        shell: Rscript {0}

      - name: Run matches script
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); source("update_matches.R")'
        shell: bash

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --quiet || (git commit -m 'Automated run to update matches' && git push)
