# Update Matches data
name: update-matches

on:
  schedule:
    - cron: '00 23 * * SUN,MON,THU'
  workflow_dispatch:

jobs:
  run-sims-script:
    name: Run R script and output matches csv
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libharfbuzz-dev libfribidi-dev
        shell: bash
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("tidyverse", "worldfootballR"))'
      - name: Run matches script
        run: |
          source('update_matches.R')
        shell: Rscript {0}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Run sims script and update csv for app' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
